name: Build and push Docker image

on:
  release:
    types: [ released, prereleased ]

env:
  DOCKER_ACCOUNT: zoraxydocker
  DOCKER_REPO: zoraxy
  DOCKER_REPO_TAG_CACHE_NAME: buildcache
  DOCKER_PLATFORMS: linux/amd64,linux/arm64
  
jobs:
  setup-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Setup building file structure
        run: |
          cp -lr $GITHUB_WORKSPACE/src/ $GITHUB_WORKSPACE/docker/src/

      - name: Build and push Docker image (Release)
        if: "!github.event.release.prerelease"
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          push: true
          platforms: ${{ env.DOCKER_PLATFORMS }}
          tags: |
            ${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:latest
            ${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:${{ github.event.release.tag_name }}
          cache-from: type=registry,ref=${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_REPO_TAG_CACHE_NAME }}
          cache-to: type=registry,ref=${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_REPO_TAG_CACHE_NAME }},mode=max

      - name: Build and push Docker image (Prerelease)
        if: "github.event.release.prerelease"
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          push: true
          platforms: ${{ env.DOCKER_PLATFORMS }}
          tags: |
            ${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:${{ github.event.release.tag_name }}
          cache-from: type=registry,ref=${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_REPO_TAG_CACHE_NAME }}
          cache-to: type=registry,ref=${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_REPO_TAG_CACHE_NAME }},mode=max

