name: Image Publisher

on:
  release:
    types: [ published ]

jobs:
  setup-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker & GHCR
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          #echo "${{ secrets.GHCR_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin
      
      - name: Setup building file structure
        run: |
          cp -r $GITHUB_WORKSPACE/src/ $GITHUB_WORKSPACE/docker/

      - name: Build the image
        run: |
          cd $GITHUB_WORKSPACE/docker/
          docker buildx create --name mainbuilder --driver docker-container --platform linux/amd64,linux/arm64 --use
          
          docker buildx build --push \
            --build-arg VERSION=${{ github.event.release.tag_name }} \
            --provenance=false \
            --platform linux/amd64,linux/arm64 \
            --tag ${{ secrets.DOCKER_USERNAME }}/zoraxy:${{ github.event.release.tag_name }} \
            --tag ${{ secrets.DOCKER_USERNAME }}/zoraxy:latest \
            # Since this is still undetermined, I will leave it commented
            #--tag ghcr.io/${{ secrets.GHCR_USERNAME }}/zoraxy:${{ steps.get_latest_release_tag.outputs.latest_tag }} \
            #--tag ghcr.io/${{ secrets.GHCR_USERNAME }}/zoraxy:latest \
            .
