name: Image Publisher

on:
  release:
    types: [ published ]

jobs:
  setup-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker & GHCR
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Setup building file structure
        run: |
          cp -r $GITHUB_WORKSPACE/src/ $GITHUB_WORKSPACE/docker/

      - name: Build the image
        run: |
          cd $GITHUB_WORKSPACE/docker/
          docker buildx create --name mainbuilder --driver docker-container --platform linux/amd64,linux/arm64 --use
          
          docker buildx build --push \
            --provenance=false \
            --platform linux/amd64,linux/arm64 \
            --tag zoraxydocker/zoraxy:${{ github.event.release.tag_name }} \
            --tag zoraxydocker/zoraxy:latest \
            .
